# Use the official Hugo image as a base
FROM klakegg/hugo:ext-alpine

# Set the working directory inside the container
WORKDIR /src

# Copy the current directory contents into the container at /src
COPY . /src

# Expose the port Hugo will run on
EXPOSE 1313

# Set the entrypoint to hugo
ENTRYPOINT ["hugo"]

# Default command to run the Hugo server
CMD ["server", "--bind", "0.0.0.0", "--baseURL=http://localhost", "--disableFastRender", "--buildDrafts", "--watch"]
